// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.270000,HLS_SYN_LAT=31,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=196,HLS_SYN_LUT=303,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] a_address0;
output   a_ce0;
input  [39:0] a_q0;
output  [2:0] b_address0;
output   b_ce0;
input  [39:0] b_q0;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15_fu_199_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] select_ln15_fu_155_p3;
reg   [2:0] select_ln15_reg_418;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] i_3_fu_163_p3;
reg   [2:0] i_3_reg_423;
wire   [0:0] icmp_ln17_fu_193_p2;
reg   [0:0] icmp_ln17_reg_439;
reg   [0:0] icmp_ln15_reg_444;
reg   [7:0] tmp_reg_453;
reg   [7:0] tmp_reg_453_pp0_iter2_reg;
reg   [7:0] tmp_1_reg_458;
reg   [7:0] tmp_2_reg_463;
reg   [7:0] tmp_2_reg_463_pp0_iter2_reg;
wire   [4:0] add_ln22_4_fu_283_p2;
reg   [4:0] add_ln22_4_reg_473;
reg   [4:0] add_ln22_4_reg_473_pp0_iter2_reg;
reg   [4:0] add_ln22_4_reg_473_pp0_iter3_reg;
reg   [4:0] add_ln22_4_reg_473_pp0_iter4_reg;
reg   [7:0] tmp_4_reg_483;
reg   [7:0] tmp_4_reg_483_pp0_iter2_reg;
reg   [7:0] tmp_5_reg_488;
reg   [7:0] tmp_6_reg_493;
reg   [7:0] tmp_6_reg_493_pp0_iter2_reg;
wire  signed [15:0] mul_ln22_1_fu_351_p2;
wire  signed [15:0] mul_ln22_3_fu_357_p2;
wire  signed [15:0] grp_fu_372_p3;
reg   [15:0] add_ln22_reg_523;
wire  signed [15:0] grp_fu_380_p3;
reg   [0:0] ap_phi_mux_icmp_ln174_phi_fu_118_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln15_fu_171_p1;
wire   [63:0] zext_ln17_fu_176_p1;
wire   [63:0] zext_ln22_12_fu_363_p1;
reg   [4:0] indvar_flatten1_fu_64;
wire   [4:0] add_ln15_1_fu_187_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [2:0] i_fu_68;
reg   [2:0] ap_sig_allocacmp_i_1;
reg   [2:0] j_fu_72;
wire   [2:0] j_3_fu_181_p2;
reg   [2:0] ap_sig_allocacmp_j_1;
reg    a_ce0_local;
reg    b_ce0_local;
reg    prod_we0_local;
(* use_dsp = "no" *) wire   [15:0] add_ln22_3_fu_367_p2;
reg    prod_ce0_local;
wire   [2:0] add_ln15_fu_149_p2;
wire   [4:0] tmp_8_fu_223_p3;
wire   [4:0] zext_ln22_10_fu_220_p1;
wire   [7:0] trunc_ln22_fu_236_p1;
wire   [7:0] tmp_3_fu_268_p3;
wire   [4:0] add_ln22_5_fu_230_p2;
wire   [4:0] zext_ln22_11_fu_280_p1;
wire   [7:0] trunc_ln22_1_fu_289_p1;
wire   [7:0] tmp_7_fu_321_p3;
wire   [7:0] mul_ln22_1_fu_351_p0;
wire   [7:0] mul_ln22_1_fu_351_p1;
wire   [7:0] mul_ln22_3_fu_357_p0;
wire   [7:0] mul_ln22_3_fu_357_p1;
wire   [15:0] add_ln22_3_fu_367_p0;
wire  signed [15:0] grp_fu_388_p3;
wire   [7:0] grp_fu_372_p0;
wire   [7:0] grp_fu_372_p1;
wire   [7:0] grp_fu_380_p0;
wire   [7:0] grp_fu_380_p1;
wire   [7:0] grp_fu_388_p0;
wire   [7:0] grp_fu_388_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_372_p00;
wire   [15:0] grp_fu_372_p10;
wire   [15:0] grp_fu_380_p00;
wire   [15:0] grp_fu_380_p10;
wire   [15:0] grp_fu_388_p00;
wire   [15:0] grp_fu_388_p10;
wire   [15:0] mul_ln22_1_fu_351_p00;
wire   [15:0] mul_ln22_1_fu_351_p10;
wire   [15:0] mul_ln22_3_fu_357_p00;
wire   [15:0] mul_ln22_3_fu_357_p10;
reg    ap_condition_412;
reg    ap_condition_91;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 indvar_flatten1_fu_64 = 5'd0;
#0 i_fu_68 = 3'd0;
#0 j_fu_72 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U1(
    .din0(mul_ln22_1_fu_351_p0),
    .din1(mul_ln22_1_fu_351_p1),
    .dout(mul_ln22_1_fu_351_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U2(
    .din0(mul_ln22_3_fu_357_p0),
    .din1(mul_ln22_3_fu_357_p1),
    .dout(mul_ln22_3_fu_357_p2)
);

matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_372_p0),
    .din1(grp_fu_372_p1),
    .din2(mul_ln22_1_fu_351_p2),
    .ce(1'b1),
    .dout(grp_fu_372_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_380_p0),
    .din1(grp_fu_380_p1),
    .din2(mul_ln22_3_fu_357_p2),
    .ce(1'b1),
    .dout(grp_fu_380_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16s_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_388_p0),
    .din1(grp_fu_388_p1),
    .din2(grp_fu_380_p3),
    .ce(1'b1),
    .dout(grp_fu_388_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_91)) begin
        i_fu_68 <= i_3_fu_163_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_91)) begin
    indvar_flatten1_fu_64 <= add_ln15_1_fu_187_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_91)) begin
    j_fu_72 <= j_3_fu_181_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln22_4_reg_473 <= add_ln22_4_fu_283_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_3_reg_423 <= i_3_fu_163_p3;
        icmp_ln15_reg_444 <= icmp_ln15_fu_199_p2;
        select_ln15_reg_418 <= select_ln15_fu_155_p3;
        tmp_1_reg_458 <= {{a_q0[23:16]}};
        tmp_2_reg_463 <= {{a_q0[31:24]}};
        tmp_4_reg_483 <= {{b_q0[15:8]}};
        tmp_5_reg_488 <= {{b_q0[23:16]}};
        tmp_6_reg_493 <= {{b_q0[31:24]}};
        tmp_reg_453 <= {{a_q0[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln22_4_reg_473_pp0_iter2_reg <= add_ln22_4_reg_473;
        add_ln22_4_reg_473_pp0_iter3_reg <= add_ln22_4_reg_473_pp0_iter2_reg;
        add_ln22_4_reg_473_pp0_iter4_reg <= add_ln22_4_reg_473_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        tmp_2_reg_463_pp0_iter2_reg <= tmp_2_reg_463;
        tmp_4_reg_483_pp0_iter2_reg <= tmp_4_reg_483;
        tmp_6_reg_493_pp0_iter2_reg <= tmp_6_reg_493;
        tmp_reg_453_pp0_iter2_reg <= tmp_reg_453;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        add_ln22_reg_523 <= grp_fu_372_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln17_reg_439 <= icmp_ln17_fu_193_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_199_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_412)) begin
            ap_phi_mux_icmp_ln174_phi_fu_118_p4 = icmp_ln17_reg_439;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln174_phi_fu_118_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln174_phi_fu_118_p4 = icmp_ln17_reg_439;
        end
    end else begin
        ap_phi_mux_icmp_ln174_phi_fu_118_p4 = icmp_ln17_reg_439;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = zext_ln15_fu_171_p1;

assign a_ce0 = a_ce0_local;

assign add_ln15_1_fu_187_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 5'd1);

assign add_ln15_fu_149_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign add_ln22_3_fu_367_p0 = grp_fu_388_p3;

assign add_ln22_3_fu_367_p2 = (add_ln22_3_fu_367_p0 + add_ln22_reg_523);

assign add_ln22_4_fu_283_p2 = (add_ln22_5_fu_230_p2 + zext_ln22_11_fu_280_p1);

assign add_ln22_5_fu_230_p2 = (tmp_8_fu_223_p3 + zext_ln22_10_fu_220_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_412 = ((icmp_ln15_reg_444 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_91 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_address0 = zext_ln17_fu_176_p1;

assign b_ce0 = b_ce0_local;

assign grp_fu_372_p0 = grp_fu_372_p00;

assign grp_fu_372_p00 = trunc_ln22_1_fu_289_p1;

assign grp_fu_372_p1 = grp_fu_372_p10;

assign grp_fu_372_p10 = trunc_ln22_fu_236_p1;

assign grp_fu_380_p0 = grp_fu_380_p00;

assign grp_fu_380_p00 = tmp_7_fu_321_p3;

assign grp_fu_380_p1 = grp_fu_380_p10;

assign grp_fu_380_p10 = tmp_3_fu_268_p3;

assign grp_fu_388_p0 = grp_fu_388_p00;

assign grp_fu_388_p00 = tmp_5_reg_488;

assign grp_fu_388_p1 = grp_fu_388_p10;

assign grp_fu_388_p10 = tmp_1_reg_458;

assign i_3_fu_163_p3 = ((ap_phi_mux_icmp_ln174_phi_fu_118_p4[0:0] == 1'b1) ? add_ln15_fu_149_p2 : ap_sig_allocacmp_i_1);

assign icmp_ln15_fu_199_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_193_p2 = ((j_3_fu_181_p2 == 3'd5) ? 1'b1 : 1'b0);

assign j_3_fu_181_p2 = (select_ln15_fu_155_p3 + 3'd1);

assign mul_ln22_1_fu_351_p0 = mul_ln22_1_fu_351_p00;

assign mul_ln22_1_fu_351_p00 = tmp_4_reg_483_pp0_iter2_reg;

assign mul_ln22_1_fu_351_p1 = mul_ln22_1_fu_351_p10;

assign mul_ln22_1_fu_351_p10 = tmp_reg_453_pp0_iter2_reg;

assign mul_ln22_3_fu_357_p0 = mul_ln22_3_fu_357_p00;

assign mul_ln22_3_fu_357_p00 = tmp_6_reg_493_pp0_iter2_reg;

assign mul_ln22_3_fu_357_p1 = mul_ln22_3_fu_357_p10;

assign mul_ln22_3_fu_357_p10 = tmp_2_reg_463_pp0_iter2_reg;

assign prod_address0 = zext_ln22_12_fu_363_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = add_ln22_3_fu_367_p2;

assign prod_we0 = prod_we0_local;

assign select_ln15_fu_155_p3 = ((ap_phi_mux_icmp_ln174_phi_fu_118_p4[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_1);

assign tmp_3_fu_268_p3 = {{a_q0[39:32]}};

assign tmp_7_fu_321_p3 = {{b_q0[39:32]}};

assign tmp_8_fu_223_p3 = {{i_3_reg_423}, {2'd0}};

assign trunc_ln22_1_fu_289_p1 = b_q0[7:0];

assign trunc_ln22_fu_236_p1 = a_q0[7:0];

assign zext_ln15_fu_171_p1 = i_3_fu_163_p3;

assign zext_ln17_fu_176_p1 = select_ln15_fu_155_p3;

assign zext_ln22_10_fu_220_p1 = i_3_reg_423;

assign zext_ln22_11_fu_280_p1 = select_ln15_reg_418;

assign zext_ln22_12_fu_363_p1 = add_ln22_4_reg_473_pp0_iter4_reg;

endmodule //matrix_mult
