[hls]
relative_roots=D:/Semester_6/HWSW/LAB3/matrix_mult_prj_solution2
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=matrix_mult/Col  
syn.directive.loop_flatten=matrix_mult/Row  


