// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.998000,HLS_SYN_LAT=81,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=148,HLS_SYN_LUT=512,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        b_address0,
        b_ce0,
        b_q0,
        b_address1,
        b_ce1,
        b_q1,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [4:0] a_address1;
output   a_ce1;
input  [7:0] a_q1;
output  [4:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [4:0] b_address1;
output   b_ce1;
input  [7:0] b_q1;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln15_fu_420_p2;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] reg_201;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] reg_205;
reg   [7:0] reg_210;
wire    ap_block_pp0_stage2_11001;
wire   [2:0] select_ln15_fu_242_p3;
reg   [2:0] select_ln15_reg_530;
wire   [4:0] trunc_ln22_fu_285_p1;
reg   [4:0] trunc_ln22_reg_536;
wire   [4:0] zext_ln22_17_fu_294_p1;
reg   [4:0] zext_ln22_17_reg_550;
reg   [7:0] a_load_2_reg_597;
wire   [4:0] add_ln22_12_fu_395_p2;
reg   [4:0] add_ln22_12_reg_612;
reg   [4:0] add_ln22_12_reg_612_pp0_iter1_reg;
reg   [7:0] b_load_3_reg_617;
wire   [0:0] icmp_ln17_fu_414_p2;
reg   [0:0] icmp_ln17_reg_627;
reg   [0:0] icmp_ln15_reg_632;
reg   [0:0] icmp_ln15_reg_632_pp0_iter1_reg;
wire   [15:0] mul_ln22_3_fu_451_p2;
reg  signed [15:0] mul_ln22_3_reg_646;
wire   [15:0] mul_ln22_1_fu_472_p2;
reg  signed [15:0] mul_ln22_1_reg_661;
wire  signed [15:0] grp_fu_487_p3;
reg  signed [15:0] add_ln22_1_reg_666;
wire  signed [15:0] grp_fu_494_p3;
reg   [15:0] add_ln22_reg_671;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] ap_phi_mux_icmp_ln174_phi_fu_194_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln22_12_fu_280_p1;
wire   [63:0] zext_ln17_fu_289_p1;
wire   [63:0] zext_ln22_22_fu_304_p1;
wire   [63:0] zext_ln22_14_fu_319_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln22_16_fu_329_p1;
wire   [63:0] zext_ln22_20_fu_339_p1;
wire   [63:0] zext_ln22_21_fu_349_p1;
wire   [63:0] zext_ln22_13_fu_362_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln22_15_fu_372_p1;
wire   [63:0] zext_ln22_19_fu_390_p1;
wire   [63:0] zext_ln22_23_fu_478_p1;
reg   [4:0] indvar_flatten1_fu_68;
wire   [4:0] add_ln15_1_fu_408_p2;
reg   [2:0] i_fu_72;
wire   [2:0] i_3_fu_250_p3;
reg   [2:0] ap_sig_allocacmp_i_1;
reg   [2:0] j_fu_76;
wire   [2:0] j_3_fu_403_p2;
reg   [2:0] ap_sig_allocacmp_j_1;
reg    a_ce0_local;
reg   [4:0] a_address0_local;
reg    a_ce1_local;
reg   [4:0] a_address1_local;
reg    b_ce1_local;
reg   [4:0] b_address1_local;
reg    b_ce0_local;
reg   [4:0] b_address0_local;
reg    prod_we0_local;
(* use_dsp = "no" *) wire   [15:0] add_ln22_3_fu_482_p2;
reg    prod_ce0_local;
wire   [2:0] add_ln15_fu_236_p2;
wire   [4:0] tmp_fu_262_p3;
wire   [5:0] zext_ln22_11_fu_270_p1;
wire   [5:0] zext_ln22_10_fu_258_p1;
wire   [5:0] add_ln22_13_fu_274_p2;
wire   [4:0] add_ln22_11_fu_298_p2;
wire   [4:0] add_ln22_5_fu_314_p2;
wire   [4:0] add_ln22_7_fu_324_p2;
wire   [4:0] add_ln22_9_fu_334_p2;
wire   [4:0] add_ln22_10_fu_344_p2;
wire   [4:0] add_ln22_4_fu_357_p2;
wire   [4:0] add_ln22_6_fu_367_p2;
wire   [3:0] zext_ln22_18_fu_381_p1;
wire   [3:0] add_ln22_8_fu_384_p2;
wire   [7:0] mul_ln22_3_fu_451_p0;
wire   [7:0] mul_ln22_3_fu_451_p1;
wire   [7:0] mul_ln22_1_fu_472_p0;
wire   [7:0] mul_ln22_1_fu_472_p1;
wire   [15:0] add_ln22_3_fu_482_p0;
wire  signed [15:0] grp_fu_501_p3;
wire   [7:0] grp_fu_487_p0;
wire   [7:0] grp_fu_487_p1;
wire   [7:0] grp_fu_494_p0;
wire   [7:0] grp_fu_494_p1;
wire   [7:0] grp_fu_501_p0;
wire   [7:0] grp_fu_501_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage1;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_487_p00;
wire   [15:0] grp_fu_487_p10;
wire   [15:0] grp_fu_494_p00;
wire   [15:0] grp_fu_494_p10;
wire   [15:0] grp_fu_501_p00;
wire   [15:0] grp_fu_501_p10;
wire   [15:0] mul_ln22_1_fu_472_p00;
wire   [15:0] mul_ln22_1_fu_472_p10;
wire   [15:0] mul_ln22_3_fu_451_p00;
wire   [15:0] mul_ln22_3_fu_451_p10;
reg    ap_condition_528;
reg    ap_condition_225;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_68 = 5'd0;
#0 i_fu_72 = 3'd0;
#0 j_fu_76 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U1(
    .din0(mul_ln22_3_fu_451_p0),
    .din1(mul_ln22_3_fu_451_p1),
    .dout(mul_ln22_3_fu_451_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U2(
    .din0(mul_ln22_1_fu_472_p0),
    .din1(mul_ln22_1_fu_472_p1),
    .dout(mul_ln22_1_fu_472_p2)
);

matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_487_p0),
    .din1(grp_fu_487_p1),
    .din2(mul_ln22_3_reg_646),
    .ce(1'b1),
    .dout(grp_fu_487_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_494_p0),
    .din1(grp_fu_494_p1),
    .din2(mul_ln22_1_reg_661),
    .ce(1'b1),
    .dout(grp_fu_494_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16s_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_501_p0),
    .din1(grp_fu_501_p1),
    .din2(add_ln22_1_reg_666),
    .ce(1'b1),
    .dout(grp_fu_501_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage1)))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_225)) begin
        i_fu_72 <= i_3_fu_250_p3;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
    indvar_flatten1_fu_68 <= 5'd0;
end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
    indvar_flatten1_fu_68 <= add_ln15_1_fu_408_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
    j_fu_76 <= 3'd0;
end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
    j_fu_76 <= j_3_fu_403_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    reg_205 <= b_q0;
end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
    reg_205 <= b_q1;
end
end

always @ (posedge ap_clk) begin
if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_210 <= b_q1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_210 <= b_q0;
    end
end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_load_2_reg_597 <= a_q1;
        b_load_3_reg_617 <= b_q0;
        icmp_ln17_reg_627 <= icmp_ln17_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln22_12_reg_612 <= add_ln22_12_fu_395_p2;
        add_ln22_12_reg_612_pp0_iter1_reg <= add_ln22_12_reg_612;
        icmp_ln15_reg_632 <= icmp_ln15_fu_420_p2;
        icmp_ln15_reg_632_pp0_iter1_reg <= icmp_ln15_reg_632;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln22_1_reg_666 <= grp_fu_487_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln22_reg_671 <= grp_fu_494_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln22_1_reg_661 <= mul_ln22_1_fu_472_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln22_3_reg_646 <= mul_ln22_3_fu_451_p2;
        select_ln15_reg_530 <= select_ln15_fu_242_p3;
        trunc_ln22_reg_536 <= trunc_ln22_fu_285_p1;
        zext_ln22_17_reg_550[2 : 0] <= zext_ln22_17_fu_294_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_201 <= a_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address0_local = zext_ln22_13_fu_362_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_address0_local = zext_ln22_16_fu_329_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address0_local = zext_ln22_12_fu_280_p1;
    end else begin
        a_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            a_address1_local = zext_ln22_15_fu_372_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            a_address1_local = zext_ln22_14_fu_319_p1;
        end else begin
            a_address1_local = 'bx;
        end
    end else begin
        a_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        a_ce1_local = 1'b1;
    end else begin
        a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_420_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln15_reg_632_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_528)) begin
            ap_phi_mux_icmp_ln174_phi_fu_194_p4 = icmp_ln17_reg_627;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln174_phi_fu_194_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln174_phi_fu_194_p4 = icmp_ln17_reg_627;
        end
    end else begin
        ap_phi_mux_icmp_ln174_phi_fu_194_p4 = icmp_ln17_reg_627;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_76;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address0_local = zext_ln22_19_fu_390_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address0_local = zext_ln22_21_fu_349_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address0_local = zext_ln22_22_fu_304_p1;
    end else begin
        b_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address1_local = zext_ln22_20_fu_339_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address1_local = zext_ln17_fu_289_p1;
    end else begin
        b_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        b_ce1_local = 1'b1;
    end else begin
        b_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = a_address0_local;

assign a_address1 = a_address1_local;

assign a_ce0 = a_ce0_local;

assign a_ce1 = a_ce1_local;

assign add_ln15_1_fu_408_p2 = (indvar_flatten1_fu_68 + 5'd1);

assign add_ln15_fu_236_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign add_ln22_10_fu_344_p2 = (zext_ln22_17_reg_550 + 5'd15);

assign add_ln22_11_fu_298_p2 = ($signed(zext_ln22_17_fu_294_p1) + $signed(5'd20));

assign add_ln22_12_fu_395_p2 = (trunc_ln22_reg_536 + zext_ln22_17_reg_550);

assign add_ln22_13_fu_274_p2 = (zext_ln22_11_fu_270_p1 + zext_ln22_10_fu_258_p1);

assign add_ln22_3_fu_482_p0 = grp_fu_501_p3;

assign add_ln22_3_fu_482_p2 = (add_ln22_3_fu_482_p0 + add_ln22_reg_671);

assign add_ln22_4_fu_357_p2 = (trunc_ln22_reg_536 + 5'd1);

assign add_ln22_5_fu_314_p2 = (trunc_ln22_reg_536 + 5'd2);

assign add_ln22_6_fu_367_p2 = (trunc_ln22_reg_536 + 5'd3);

assign add_ln22_7_fu_324_p2 = (trunc_ln22_reg_536 + 5'd4);

assign add_ln22_8_fu_384_p2 = (zext_ln22_18_fu_381_p1 + 4'd5);

assign add_ln22_9_fu_334_p2 = (zext_ln22_17_reg_550 + 5'd10);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_225 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_528 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_632 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign b_address0 = b_address0_local;

assign b_address1 = b_address1_local;

assign b_ce0 = b_ce0_local;

assign b_ce1 = b_ce1_local;

assign grp_fu_487_p0 = grp_fu_487_p00;

assign grp_fu_487_p00 = reg_210;

assign grp_fu_487_p1 = grp_fu_487_p10;

assign grp_fu_487_p10 = a_q0;

assign grp_fu_494_p0 = grp_fu_494_p00;

assign grp_fu_494_p00 = reg_205;

assign grp_fu_494_p1 = grp_fu_494_p10;

assign grp_fu_494_p10 = reg_201;

assign grp_fu_501_p0 = grp_fu_501_p00;

assign grp_fu_501_p00 = reg_210;

assign grp_fu_501_p1 = grp_fu_501_p10;

assign grp_fu_501_p10 = a_load_2_reg_597;

assign i_3_fu_250_p3 = ((ap_phi_mux_icmp_ln174_phi_fu_194_p4[0:0] == 1'b1) ? add_ln15_fu_236_p2 : ap_sig_allocacmp_i_1);

assign icmp_ln15_fu_420_p2 = ((indvar_flatten1_fu_68 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_414_p2 = ((j_3_fu_403_p2 == 3'd5) ? 1'b1 : 1'b0);

assign j_3_fu_403_p2 = (select_ln15_reg_530 + 3'd1);

assign mul_ln22_1_fu_472_p0 = mul_ln22_1_fu_472_p00;

assign mul_ln22_1_fu_472_p00 = reg_205;

assign mul_ln22_1_fu_472_p1 = mul_ln22_1_fu_472_p10;

assign mul_ln22_1_fu_472_p10 = reg_201;

assign mul_ln22_3_fu_451_p0 = mul_ln22_3_fu_451_p00;

assign mul_ln22_3_fu_451_p00 = b_load_3_reg_617;

assign mul_ln22_3_fu_451_p1 = mul_ln22_3_fu_451_p10;

assign mul_ln22_3_fu_451_p10 = a_q1;

assign prod_address0 = zext_ln22_23_fu_478_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = add_ln22_3_fu_482_p2;

assign prod_we0 = prod_we0_local;

assign select_ln15_fu_242_p3 = ((ap_phi_mux_icmp_ln174_phi_fu_194_p4[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_1);

assign tmp_fu_262_p3 = {{i_3_fu_250_p3}, {2'd0}};

assign trunc_ln22_fu_285_p1 = add_ln22_13_fu_274_p2[4:0];

assign zext_ln17_fu_289_p1 = select_ln15_fu_242_p3;

assign zext_ln22_10_fu_258_p1 = i_3_fu_250_p3;

assign zext_ln22_11_fu_270_p1 = tmp_fu_262_p3;

assign zext_ln22_12_fu_280_p1 = add_ln22_13_fu_274_p2;

assign zext_ln22_13_fu_362_p1 = add_ln22_4_fu_357_p2;

assign zext_ln22_14_fu_319_p1 = add_ln22_5_fu_314_p2;

assign zext_ln22_15_fu_372_p1 = add_ln22_6_fu_367_p2;

assign zext_ln22_16_fu_329_p1 = add_ln22_7_fu_324_p2;

assign zext_ln22_17_fu_294_p1 = select_ln15_fu_242_p3;

assign zext_ln22_18_fu_381_p1 = select_ln15_reg_530;

assign zext_ln22_19_fu_390_p1 = add_ln22_8_fu_384_p2;

assign zext_ln22_20_fu_339_p1 = add_ln22_9_fu_334_p2;

assign zext_ln22_21_fu_349_p1 = add_ln22_10_fu_344_p2;

assign zext_ln22_22_fu_304_p1 = add_ln22_11_fu_298_p2;

assign zext_ln22_23_fu_478_p1 = add_ln22_12_reg_612_pp0_iter1_reg;

always @ (posedge ap_clk) begin
    zext_ln22_17_reg_550[4:3] <= 2'b00;
end

endmodule //matrix_mult
