# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Semester_6/HWSW/LAB2/zynq_interrupts/zynq_interrupts.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_1_0/zynq_interrupt_system_axi_gpio_1_0.xci
# IP: The module: 'zynq_interrupt_system_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Semester_6/HWSW/LAB2/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_1_0/zynq_interrupt_system_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Semester_6/HWSW/LAB2/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_1_0/zynq_interrupt_system_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Semester_6/HWSW/LAB2/zynq_interrupts/zynq_interrupts.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_1_0/zynq_interrupt_system_axi_gpio_1_0.xci
# IP: The module: 'zynq_interrupt_system_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Semester_6/HWSW/LAB2/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_1_0/zynq_interrupt_system_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Semester_6/HWSW/LAB2/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_gpio_1_0/zynq_interrupt_system_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
