-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (39 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (39 downto 0);
    prod_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    prod_ce0 : OUT STD_LOGIC;
    prod_we0 : OUT STD_LOGIC;
    prod_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.270000,HLS_SYN_LAT=31,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=196,HLS_SYN_LUT=303,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv40_8 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000001000";
    constant ap_const_lv40_10 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000010000";
    constant ap_const_lv40_18 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000011000";
    constant ap_const_lv40_20 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000100000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln15_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln15_fu_155_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln15_reg_418 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_3_fu_163_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_3_reg_423 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln17_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_439 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_453 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_453_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_458 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_463 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_463_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln22_4_fu_283_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_4_reg_473 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_4_reg_473_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_4_reg_473_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_4_reg_473_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_reg_483 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_483_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_488 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_reg_493 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_reg_493_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln22_1_fu_351_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln22_3_fu_357_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_372_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln22_reg_523 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_380_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_icmp_ln174_phi_fu_118_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln15_fu_171_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln17_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln22_12_fu_363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_64 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln15_1_fu_187_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_fu_72 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_3_fu_181_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal a_ce0_local : STD_LOGIC;
    signal b_ce0_local : STD_LOGIC;
    signal prod_we0_local : STD_LOGIC;
    signal add_ln22_3_fu_367_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp : string;
    attribute use_dsp of add_ln22_3_fu_367_p2 : signal is "no";
    signal prod_ce0_local : STD_LOGIC;
    signal add_ln15_fu_149_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_223_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln22_10_fu_220_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln22_fu_236_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_268_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln22_5_fu_230_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln22_11_fu_280_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln22_1_fu_289_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_321_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln22_1_fu_351_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln22_1_fu_351_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln22_3_fu_357_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln22_3_fu_357_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln22_3_fu_367_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_388_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_372_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_372_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_380_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_380_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_388_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_372_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_372_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_380_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_380_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_388_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_388_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln22_1_fu_351_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln22_1_fu_351_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln22_3_fu_357_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln22_3_fu_357_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_412 : BOOLEAN;
    signal ap_condition_91 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_8ns_8ns_16_1_1_U1 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln22_1_fu_351_p0,
        din1 => mul_ln22_1_fu_351_p1,
        dout => mul_ln22_1_fu_351_p2);

    mul_8ns_8ns_16_1_1_U2 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln22_3_fu_357_p0,
        din1 => mul_ln22_3_fu_357_p1,
        dout => mul_ln22_3_fu_357_p2);

    mac_muladd_8ns_8ns_16s_16_4_1_U3 : component matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_372_p0,
        din1 => grp_fu_372_p1,
        din2 => mul_ln22_1_fu_351_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_372_p3);

    mac_muladd_8ns_8ns_16s_16_4_1_U4 : component matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_380_p0,
        din1 => grp_fu_380_p1,
        din2 => mul_ln22_3_fu_357_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_380_p3);

    mac_muladd_8ns_8ns_16s_16_4_1_U5 : component matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_388_p0,
        din1 => grp_fu_388_p1,
        din2 => grp_fu_380_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_388_p3);

    flow_control_loop_pipe_U : component matrix_mult_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_91)) then
                i_fu_68 <= i_3_fu_163_p3;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_91)) then
                indvar_flatten1_fu_64 <= add_ln15_1_fu_187_p2;
            end if;
        end if;
    end process;

    j_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_91)) then
                j_fu_72 <= j_3_fu_181_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln22_4_reg_473 <= add_ln22_4_fu_283_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_3_reg_423 <= i_3_fu_163_p3;
                icmp_ln15_reg_444 <= icmp_ln15_fu_199_p2;
                select_ln15_reg_418 <= select_ln15_fu_155_p3;
                tmp_1_reg_458 <= a_q0(23 downto 16);
                tmp_2_reg_463 <= a_q0(31 downto 24);
                tmp_4_reg_483 <= b_q0(15 downto 8);
                tmp_5_reg_488 <= b_q0(23 downto 16);
                tmp_6_reg_493 <= b_q0(31 downto 24);
                tmp_reg_453 <= a_q0(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln22_4_reg_473_pp0_iter2_reg <= add_ln22_4_reg_473;
                add_ln22_4_reg_473_pp0_iter3_reg <= add_ln22_4_reg_473_pp0_iter2_reg;
                add_ln22_4_reg_473_pp0_iter4_reg <= add_ln22_4_reg_473_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                tmp_2_reg_463_pp0_iter2_reg <= tmp_2_reg_463;
                tmp_4_reg_483_pp0_iter2_reg <= tmp_4_reg_483;
                tmp_6_reg_493_pp0_iter2_reg <= tmp_6_reg_493;
                tmp_reg_453_pp0_iter2_reg <= tmp_reg_453;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                add_ln22_reg_523 <= grp_fu_372_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln17_reg_439 <= icmp_ln17_fu_193_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_address0 <= zext_ln15_fu_171_p1(3 - 1 downto 0);
    a_ce0 <= a_ce0_local;

    a_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            a_ce0_local <= ap_const_logic_1;
        else 
            a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln15_1_fu_187_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv5_1));
    add_ln15_fu_149_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv3_1));
    add_ln22_3_fu_367_p0 <= grp_fu_388_p3;
    add_ln22_3_fu_367_p2 <= std_logic_vector(unsigned(add_ln22_3_fu_367_p0) + unsigned(add_ln22_reg_523));
    add_ln22_4_fu_283_p2 <= std_logic_vector(unsigned(add_ln22_5_fu_230_p2) + unsigned(zext_ln22_11_fu_280_p1));
    add_ln22_5_fu_230_p2 <= std_logic_vector(unsigned(tmp_8_fu_223_p3) + unsigned(zext_ln22_10_fu_220_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_412_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln15_reg_444, ap_block_pp0_stage0)
    begin
                ap_condition_412 <= ((icmp_ln15_reg_444 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_91_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_91 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln15_fu_199_p2)
    begin
        if (((icmp_ln15_fu_199_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln174_phi_fu_118_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_reg_439, ap_loop_init, ap_condition_412)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_412)) then 
                ap_phi_mux_icmp_ln174_phi_fu_118_p4 <= icmp_ln17_reg_439;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln174_phi_fu_118_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln174_phi_fu_118_p4 <= icmp_ln17_reg_439;
            end if;
        else 
            ap_phi_mux_icmp_ln174_phi_fu_118_p4 <= icmp_ln17_reg_439;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_64)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_64;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_72;
        end if; 
    end process;

    b_address0 <= zext_ln17_fu_176_p1(3 - 1 downto 0);
    b_ce0 <= b_ce0_local;

    b_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_ce0_local <= ap_const_logic_1;
        else 
            b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_372_p0 <= grp_fu_372_p00(8 - 1 downto 0);
    grp_fu_372_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln22_1_fu_289_p1),16));
    grp_fu_372_p1 <= grp_fu_372_p10(8 - 1 downto 0);
    grp_fu_372_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln22_fu_236_p1),16));
    grp_fu_380_p0 <= grp_fu_380_p00(8 - 1 downto 0);
    grp_fu_380_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_321_p3),16));
    grp_fu_380_p1 <= grp_fu_380_p10(8 - 1 downto 0);
    grp_fu_380_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_268_p3),16));
    grp_fu_388_p0 <= grp_fu_388_p00(8 - 1 downto 0);
    grp_fu_388_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_488),16));
    grp_fu_388_p1 <= grp_fu_388_p10(8 - 1 downto 0);
    grp_fu_388_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_458),16));
    i_3_fu_163_p3 <= 
        add_ln15_fu_149_p2 when (ap_phi_mux_icmp_ln174_phi_fu_118_p4(0) = '1') else 
        ap_sig_allocacmp_i_1;
    icmp_ln15_fu_199_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv5_18) else "0";
    icmp_ln17_fu_193_p2 <= "1" when (j_3_fu_181_p2 = ap_const_lv3_5) else "0";
    j_3_fu_181_p2 <= std_logic_vector(unsigned(select_ln15_fu_155_p3) + unsigned(ap_const_lv3_1));
    mul_ln22_1_fu_351_p0 <= mul_ln22_1_fu_351_p00(8 - 1 downto 0);
    mul_ln22_1_fu_351_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_483_pp0_iter2_reg),16));
    mul_ln22_1_fu_351_p1 <= mul_ln22_1_fu_351_p10(8 - 1 downto 0);
    mul_ln22_1_fu_351_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_453_pp0_iter2_reg),16));
    mul_ln22_3_fu_357_p0 <= mul_ln22_3_fu_357_p00(8 - 1 downto 0);
    mul_ln22_3_fu_357_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_reg_493_pp0_iter2_reg),16));
    mul_ln22_3_fu_357_p1 <= mul_ln22_3_fu_357_p10(8 - 1 downto 0);
    mul_ln22_3_fu_357_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_463_pp0_iter2_reg),16));
    prod_address0 <= zext_ln22_12_fu_363_p1(5 - 1 downto 0);
    prod_ce0 <= prod_ce0_local;

    prod_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            prod_ce0_local <= ap_const_logic_1;
        else 
            prod_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    prod_d0 <= add_ln22_3_fu_367_p2;
    prod_we0 <= prod_we0_local;

    prod_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            prod_we0_local <= ap_const_logic_1;
        else 
            prod_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln15_fu_155_p3 <= 
        ap_const_lv3_0 when (ap_phi_mux_icmp_ln174_phi_fu_118_p4(0) = '1') else 
        ap_sig_allocacmp_j_1;
    tmp_3_fu_268_p3 <= a_q0(39 downto 32);
    tmp_7_fu_321_p3 <= b_q0(39 downto 32);
    tmp_8_fu_223_p3 <= (i_3_reg_423 & ap_const_lv2_0);
    trunc_ln22_1_fu_289_p1 <= b_q0(8 - 1 downto 0);
    trunc_ln22_fu_236_p1 <= a_q0(8 - 1 downto 0);
    zext_ln15_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_fu_163_p3),64));
    zext_ln17_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln15_fu_155_p3),64));
    zext_ln22_10_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_423),5));
    zext_ln22_11_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln15_reg_418),5));
    zext_ln22_12_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln22_4_reg_473_pp0_iter4_reg),64));
end behav;
