# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Semester_6/HWSW/LAB4/led.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_my_counter_0_2/system_my_counter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_my_counter_0_2 || ORIG_REF_NAME==system_my_counter_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_2/system_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_2 || ORIG_REF_NAME==system_axi_smc_2} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_2 || ORIG_REF_NAME==system_rst_ps7_0_50M_2} -quiet] -quiet

# XDC: d:/Semester_6/HWSW/LAB4/axi_counter_zybo/axi_counter_zybo.gen/sources_1/bd/system/system_ooc.xdc
