-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    prod_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    prod_ce0 : OUT STD_LOGIC;
    prod_we0 : OUT STD_LOGIC;
    prod_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.404250,HLS_SYN_LAT=686,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=55,HLS_SYN_LUT=203,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln15_fu_141_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln15_reg_271 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln15_1_fu_159_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln15_1_reg_276 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln17_fu_171_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln17_reg_285 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln22_2_fu_177_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln22_2_reg_290 : STD_LOGIC_VECTOR (4 downto 0);
    signal prod_addr_reg_295 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_fu_201_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln20_reg_303 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_253_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal j_reg_92 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln15_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_reg_103 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln17_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_114 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln22_3_fu_186_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln22_5_fu_216_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln22_6_fu_240_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_50 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal a_ce0_local : STD_LOGIC;
    signal b_ce0_local : STD_LOGIC;
    signal prod_we0_local : STD_LOGIC;
    signal prod_ce0_local : STD_LOGIC;
    signal tmp_fu_151_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln15_fu_147_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_1_fu_181_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln22_4_fu_207_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_2_fu_211_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_221_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_4_fu_229_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln22_3_fu_235_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_253_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_253_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal grp_fu_253_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_253_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    mac_muladd_8ns_8ns_16s_16_4_1_U1 : component matrix_mult_mac_muladd_8ns_8ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_253_p0,
        din1 => grp_fu_253_p1,
        din2 => empty_reg_114,
        ce => ap_const_logic_1,
        dout => grp_fu_253_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    empty_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                empty_reg_114 <= grp_fu_253_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln17_fu_165_p2 = ap_const_lv1_0))) then 
                empty_reg_114 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    i_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_50 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln17_fu_165_p2 = ap_const_lv1_1))) then 
                i_fu_50 <= add_ln15_reg_271;
            end if; 
        end if;
    end process;

    j_reg_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln20_fu_195_p2 = ap_const_lv1_1))) then 
                j_reg_92 <= add_ln17_reg_285;
            elsif (((icmp_ln15_fu_135_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_92 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    k_reg_103_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                k_reg_103 <= add_ln20_reg_303;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln17_fu_165_p2 = ap_const_lv1_0))) then 
                k_reg_103 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln15_1_reg_276 <= add_ln15_1_fu_159_p2;
                add_ln15_reg_271 <= add_ln15_fu_141_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln17_reg_285 <= add_ln17_fu_171_p2;
                prod_addr_reg_295 <= zext_ln22_3_fu_186_p1(5 - 1 downto 0);
                    zext_ln22_2_reg_290(2 downto 0) <= zext_ln22_2_fu_177_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln20_reg_303 <= add_ln20_fu_201_p2;
            end if;
        end if;
    end process;
    zext_ln22_2_reg_290(4 downto 3) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln15_fu_135_p2, icmp_ln20_fu_195_p2, icmp_ln17_fu_165_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln15_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln17_fu_165_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln20_fu_195_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    a_address0 <= zext_ln22_5_fu_216_p1(5 - 1 downto 0);
    a_ce0 <= a_ce0_local;

    a_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            a_ce0_local <= ap_const_logic_1;
        else 
            a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln15_1_fu_159_p2 <= std_logic_vector(unsigned(tmp_fu_151_p3) + unsigned(zext_ln15_fu_147_p1));
    add_ln15_fu_141_p2 <= std_logic_vector(unsigned(i_fu_50) + unsigned(ap_const_lv3_1));
    add_ln17_fu_171_p2 <= std_logic_vector(unsigned(j_reg_92) + unsigned(ap_const_lv3_1));
    add_ln20_fu_201_p2 <= std_logic_vector(unsigned(k_reg_103) + unsigned(ap_const_lv3_1));
    add_ln22_1_fu_181_p2 <= std_logic_vector(unsigned(add_ln15_1_reg_276) + unsigned(zext_ln22_2_fu_177_p1));
    add_ln22_2_fu_211_p2 <= std_logic_vector(unsigned(add_ln15_1_reg_276) + unsigned(zext_ln22_4_fu_207_p1));
    add_ln22_3_fu_235_p2 <= std_logic_vector(unsigned(add_ln22_4_fu_229_p2) + unsigned(zext_ln22_2_reg_290));
    add_ln22_4_fu_229_p2 <= std_logic_vector(unsigned(tmp_1_fu_221_p3) + unsigned(zext_ln22_4_fu_207_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln15_fu_135_p2)
    begin
        if (((icmp_ln15_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln15_fu_135_p2)
    begin
        if (((icmp_ln15_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_address0 <= zext_ln22_6_fu_240_p1(5 - 1 downto 0);
    b_ce0 <= b_ce0_local;

    b_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            b_ce0_local <= ap_const_logic_1;
        else 
            b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_253_p0 <= grp_fu_253_p00(8 - 1 downto 0);
    grp_fu_253_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_q0),16));
    grp_fu_253_p1 <= grp_fu_253_p10(8 - 1 downto 0);
    grp_fu_253_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_q0),16));
    icmp_ln15_fu_135_p2 <= "1" when (i_fu_50 = ap_const_lv3_5) else "0";
    icmp_ln17_fu_165_p2 <= "1" when (j_reg_92 = ap_const_lv3_5) else "0";
    icmp_ln20_fu_195_p2 <= "1" when (k_reg_103 = ap_const_lv3_5) else "0";
    prod_address0 <= prod_addr_reg_295;
    prod_ce0 <= prod_ce0_local;

    prod_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            prod_ce0_local <= ap_const_logic_1;
        else 
            prod_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    prod_d0 <= empty_reg_114;
    prod_we0 <= prod_we0_local;

    prod_we0_local_assign_proc : process(ap_CS_fsm_state4, icmp_ln20_fu_195_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln20_fu_195_p2 = ap_const_lv1_1))) then 
            prod_we0_local <= ap_const_logic_1;
        else 
            prod_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_221_p3 <= (k_reg_103 & ap_const_lv2_0);
    tmp_fu_151_p3 <= (i_fu_50 & ap_const_lv2_0);
    zext_ln15_fu_147_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_50),5));
    zext_ln22_2_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_92),5));
    zext_ln22_3_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln22_1_fu_181_p2),64));
    zext_ln22_4_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_reg_103),5));
    zext_ln22_5_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln22_2_fu_211_p2),64));
    zext_ln22_6_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln22_3_fu_235_p2),64));
end behav;
