# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Semester_6/HWSW/LAB4/axi_counter_zybo/axi_counter_zybo.srcs/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
# IP: The module: 'system_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Semester_6/HWSW/LAB4/axi_counter_zybo/axi_counter_zybo.gen/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Semester_6/HWSW/LAB4/axi_counter_zybo/axi_counter_zybo.srcs/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
# IP: The module: 'system_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Semester_6/HWSW/LAB4/axi_counter_zybo/axi_counter_zybo.gen/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
